### ISSUE TITLE
TypeError: Cannot read property 'normalize' of undefined

### ISSUE THREAD

**Issue by kertal** [requirejs/r.js#790]
I've got problems building a bundle with the require.js optimizer. I want to exclude the **xy** module with by the following settings: 

```
 "paths": {
        "xy": "empty:",
      }
 "exclude": ["xy"] 
```

this works except with the following:

```
define(['xy/ready!'], function(xy){});
```

then the optimizer r.js throws a error message (r.js:1206:35)

```
 TypeError: Cannot read property 'normalize' of undefined
```

i there another workaround possible for excluding 'xy/ready!'?

Thanks & Best,
Matthias

**Comment by Legends** [comment]
looks like it's a dead project...?

**Comment by jrburke** [comment]
This project is mostly getting maintenance updates to fix some smaller issues. There have been gaps in time where issue processing was not done thoroughly too, like when this issue was filed.

For this particular issue, it is a bit unclear what the desired outcome is. If the goal is to use the 'xy/ready' loader plugin just in the build, but then exclude it from the output, that has been a bit tricky to sort out. Depending on the type of loader plugin, sometimes those are still needed after a build. But also, the way to exclude it after the build is not very straightforward. It might be enough to just do exclude: ['xy/ready'], and not do the paths config, since the loader plugin is needed for the build.

Closing as a discussion ticket, but feel free to continue discussion here.
