### ISSUE TITLE
Pragma does not remove "use strict" from file contents

### ISSUE THREAD

**Issue by fab1o** [requirejs/r.js#915]
Setting the **useStrict****:** **false** option does not remove **"use strict"** from file contents, as described here: [Set the useStrict option in the build options](https://github.com/nesk/network.js/commit/64c6c06b11fce78158bab1b8d1d1b0f42bba0a80)

This option is not doing anything. Version 2.2.0

**Comment by fab1o** [comment]
I just noticed it has been fixed on branch [**dev2.1**](https://github.com/requirejs/r.js/blob/dev2.1/build/jslib/pragma.js)

**Comment by jrburke** [comment]
This seems to undo the change done for #689, specifically, 'use strict' is now only stripped at the top level, not inside functions. At least as well as a regexp can do for that sort of thing.

If you have a case where it should be stripping the 'use strict' at the top level and it is not, then an example of the code would be helpful to sort out what can be done.

**Comment by fab1o** [comment]
All of our js files follow this pattern:


```
define("app.js", [
    "app/constants",
], function (
    constants
) {
    "use strict";

....

});
```

**Comment by jrburke** [comment]
OK, yes that form is the kind that we don't want to strip out the use strict because it changes the behavior of the code, can break things, which is what motivated the current approach in the code.

You can also use the onBuildWrite hook in the r.js build config to do your own regexp to remove what you want.
