### ISSUE TITLE
I can't use use as a global module

### ISSUE THREAD

**Issue by lynnic26** [requirejs/r.js#925]
After I have installed r.js like this
`npm install -g requirejs`
I still cannot use the command `node r.js -o xxxxxx`
It says that **cannot find r.js module in local working direcotory**
I don't know why 
Isn't that the r.js is a global module when I use `-g`?

**Comment by jrburke** [comment]
If you are on Windows, then you may need to type r.js.cmd, or use DOSKEY, info here:
http://requirejs.org/docs/optimization.html#download

Closing as a discussion ticket, but feel free to continue discussion here, and we can reopen if we identify a code change.

**Comment by ScottFreeCode** [comment]
Re. Windows, I thought the portable way to use r.js was `r_js` (because `r.js.cmd` won't work on 'nixy OSes)?

However, it's also worth pointing out here that, aside from which version of the r.js is compatible with which operating system, commandline tools installed by NPM should generally be run *without* `node` at the beginning.

**Comment by jrburke** [comment]
Ah right, I forgot that "r_js" was added as another alias for the bin command, that should work too.
