### ISSUE TITLE
Error importing webpack modules with some dependencies

### ISSUE THREAD

**Issue by robertmesserle** [requirejs/r.js#931]
The issue here is a bit tricky to describe, but it can easily be recreated by attempting to require [Microm](https://github.com/zzarcon/microm).  Our code worked properly in development, but after running through `r.js`, it resulted in [Mismatched anonymous define() modules](http://requirejs.org/docs/errors.html#mismatch).

The error seems to occur because of [this](https://github.com/zzarcon/microm/blob/master/dist/microm.js#L1143) in the Microm dist file.  This comes from Microm depending on [webrtc-adapter](https://github.com/webrtc/adapter).  By moving that dependency into our own project and removing it from Microm, this resolved the issue.

I wasn't entirely sure if this issue belonged on `r.js` since it requires a setup of `require => webpack => require` in order to reproduce it, but since this code works fine with require, it seemed like it should also work in r.js.

**Comment by jrburke** [comment]
If webpack is generating that file, then my first thought is that it should create a locally `var define = undefined` inside the closure it creates (maybe around [line 11](https://github.com/zzarcon/microm/blob/master/dist/microm.js#L11)?) so that any of its interior modules that may have had their own UMD block do not try to access the global define. I think this is pretty standard practice, for example I think there is an option or just a default in browserify that does that. Maybe there is something equivalent for webpack. I don't know that tool to know off the top of my head.

If it is not an option, then if there is an option for you to provide a file or text to put in a preamble that might end up around line 11 or at least at the top of the webrtc-adapter file, that would also work.

Going to close for now as I think this is an issue that should be solved at the webpack stage, but feel free to continue the conversation here and we can reopen if needed.
