### ISSUE TITLE
Optimizer requires that plugin.write does not call any asynchronous code

### ISSUE THREAD

**Issue by conman124** [requirejs/r.js#934]
Hi,

I am developing a plugin for require. I would like to call some asynchronous code in my module's write function, but I noticed that if I do not call the write callback with my output before returning from the write function, my output does not get put into the built file.  Is this intentional?  Is there a workaround?

For example, this would not work (obviously, I'd be doing something other than calling setTimeout, but you get the point! :) )
```javascript
var myPlugin = {
...
   write: function(pluginName, moduleName, write) {
      setTimeout(function() {
         write("This was excuted asynchronously!");
      }, 100);
   }
...
}
```

Thanks!

**Comment by jrburke** [comment]
Unfortunately the plugin's `write` method is restricted to synchronous operation only, to make sure the contents of the built file are written out in the correct sequence. It is probably possible to think of a way to do it so that async processing would be allowed, but it would be a significant code change, no plans to do so at this time.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by conman124** [comment]
Thank you for your response.  That is a valid reason for the restriction.  I just wasn't sure if it was intentional and I was unable to find any info about it.  So, hopefully anyone else with the same issue will see this.
