### ISSUE TITLE
Map configuration leads to broken dependencies

### ISSUE THREAD

**Issue by soulmerge** [requirejs/r.js#944]
The dependencies of my requirejs plugins are `null` if the plugins themselves are in the `include` list. I have created a [minimal test case](https://github.com/requirejs/r.js/files/575929/requirejs-map-bug.zip) to demonstrate the bug. The build works if I change the `include` section from this:
```
    "include": ["lib/foo", "a"]
```
to this:
```
    "include": ["a"]
```
The result should be the same in both cases, as "a.js" depends on "lib/foo!a.js", but the build fails in the first case:
```
soulmerge@ca:~/tmp/requirejs$ r.js -o require.conf

Tracing dependencies for: /home/soulmerge/tmp/requirejs/out.js
TypeError: Cannot read property 'load' of undefined
In module tree:
    a
      lib/foo

Error: TypeError: Cannot read property 'load' of undefined
In module tree:
define(['text', 'module'], function(text, module) {
    a
      lib/foo

    at Object.load (eval at <anonymous> (/home/soulmerge/node_modules/requirejs/bin/r.js:25271:33), <anonymous>:12:21)
```

**Comment by jrburke** [comment]
With the "lib/foo" first in the `include` option, the optimizer traces it and its dependencies first. Since the modules are not used a loader plugin yet, it does not fully evaluate the source of these modules, but just parses out the dependencies to trace.

Then "a" is processed. It does use "lib/foo" as a loader plugin. So the loader will then go and an "undefine" the previous "lib/foo" module and reload it as a full source module. However, the undefining process is shallow, just applies it to the loader plugin and not its dependencies. So when "lib/foo" asks for "text", it gets the simplified parsed version of "text" from the first pass, which is not a full module execution.

Workarounds for this particular case, but which I can appreciate may not translate to the actual case where it shows up in a project:

* write the include as `include: ['a', 'lib/foo']`. By placing the loader plugin second, since 'a' will have already triggered the load of "lib/foo" as a loader plugin it works out.
* just leave off the loader plugin from `include` since `a` refers to it already.

I think the fix will be sorting out how to do a deep dependency trace for loader plugins and undefine them all. The map config in this case is not the issue but the lack of an undefine for the loader plugin **and** all of its deep dependencies.

I am not sure if this will get into the next point release, but tentatively placing it that milestone just so I can spend more time on it, do not have enough time for it now.

**Comment by soulmerge** [comment]
Thank you for the analysis if this issue. We want to make use of r.js in the automatic deployment process of our project. The application keeps track of all javascript files and creates the r.js configuration automatically by dumping the file paths into the "include" section. Looks like I will need to add a configuration value to our deployment process for pointing out all requirejs modules. Those will then end up at the end of the list.

The interesting part is: the bug seems to be tied to the "map" configuration somehow: The build completes successfully if I:
* change the dependency of `lib/foo` from `text` to `lib/text` and
* remove the "map" section of the build configuration.
