### ISSUE TITLE
Update UglifyJS

### ISSUE THREAD

**Issue by jscharett** [requirejs/r.js#959]
Looks like UglifyJS 3.X has been released.  Any plans on updating to support it?

**Comment by jrburke** [comment]
There seem to be two options, an uglify-js or [uglify-es](https://www.npmjs.com/package/uglify-es), and both use the 3.x API of uglify which is not backwards compatible with 2.x.

So the concerns would be:

* Since it sounds like it has a breaking API, should r.js be major version revved to 3.x so that people who are passing uglify args via r.js config are not broken? Seems like the version should be revved if uglify is bundled with r.js.
* Should the -es or -js version be used? I am concerned that the -es version is still new, may still have unpleasant bugs.

Given these concerns and that JS packages are more easily used with each other now via node/npm vs when r.js was started, maybe the answer is to version rev r.js to 3.x but remove any built in minifier so that way the choice of minifier is decoupled from the module bundling tool.

I am sort of favoring that option, but open to hearing reasons why a minifier should still be in r.js.

**Comment by ScottFreeCode** [comment]
I, for one, would gladly bundle and minimize as separate steps in order to have a better choice of minifier. (Although, it must be admitted, that can be done now by turning off minimization when running r.js...)

**Comment by jscharett** [comment]
I like the thought of being able to choose a minifier. It might be nice to still include one as a default for simplicity, but be able to easily override it.

As for es vs js, I thought es was the new version, targeting es6 and js was the older one targeting es5 syntax. If made configuable, maybe target the js as default for better backwards compatability and stability. Users could override with es if they so choose so.

**Comment by wstoettinger** [comment]
Any updates on that?

**Comment by nelsieborja** [comment]
Came across same requirement today so just want to share how I made it possible with grunt. First I did it via shell (as suggested above) but then I thought it doesn't seem cool and there should be better way, so here it is:

First need to install uglify-es `npm install uglify-es --save-dev`
Then in Grunt file do:
`requirejs: {
    ...
    options: {
        out: function(text, sourceMapText) {
                  var UglifyJS = require("uglify-es"),
                         uglified = UglifyJS.minify(text);
                  grunt.file.write(<filepath>, uglified.code);
                }
    }
    ...
}`

**Comment by nelson777** [comment]
And how would I translate

`out: "<%= dest %>/js/whatever.js",`

to `<filepath>` in this solution ?

**Comment by jrburke** [comment]
Since there seems to be a desire to keep a bundled uglify, for backcompat reasons to avoid breaking people's config where they could be passing config to uglify, I will keep the uglify-js 2.x series in the code for now. I also added some docs and extra info on an uglify parse error about trying `optimize: 'none'` and using an ES2015+compatible minifier after the r.js step.

I also updated latest master to uglify 2.8.29. Release 2.3.4 includes an esprima update so at least parsing to build the combined file will work with latest JS/ES syntax.

Going to close this ticket now, and going forward the guidance will be to use optimize: none with a separate minifier if wanting to minify ES2015+ code.

**Comment by zam6ak** [comment]
Is there a workaround to use approach mentioned in https://github.com/requirejs/r.js/issues/959#issuecomment-317424745
but with modules?
you can't use "out" is "modules" option is used.....

**Comment by Amphiluke** [comment]
I’ve found it handy to make use of the [`onBuildWrite` hook](https://github.com/requirejs/r.js/blob/13c11deea71755743c98c14ca66cd3b54df9b849/build/example.build.js#L553) for minification of the bundled modules written in ES2015+. This is _roughly_ how the build file may look with [terser](https://github.com/terser-js/terser) used as a minification tool:

```javascript
({
    // any options you need...

    optimize: "none", // disable standard uglifyjs optimisations
    onBuildWrite(moduleName, path, contents) {
        // r.js overrides `require` saving the original function as `require.nodeRequire`
        let terser = require.nodeRequire("terser");
        let result = terser.minify(contents);
        if (result.error) {
            throw new Error(result.error);
        }
        return result.code;
    }
})
```

**Comment by ahayes91** [comment]
> Came across with the same requirement today so just want to share how I made it possible with grunt. First I did it via shell (as suggested above) but then I thought it doesn't seem cool and there should be better way, so here it is:
> 
> First need to install uglify-es `npm install uglify-es --save-dev`
> Then in Grunt file do:
> 
> ```
> requirejs: { 
>     options: {
>         optimize: 'none',
>         out: function(text, sourceMapText) {
>             var UglifyJS = require('uglify-es'),
>                 uglified = UglifyJS.minify(text);
> 
>             grunt.file.write(<filepath>, uglified.code);
>         }
>     }
> }
> ```

Does `sourceMapText` need to be used in the UglifyJS.minify function? Should it correspond to one of these options? https://github.com/mishoo/UglifyJS2#source-map-options

**Comment by easyfrog** [comment]
> I’ve found it handy to make use of the [`onBuildWrite` hook](https://github.com/requirejs/r.js/blob/13c11deea71755743c98c14ca66cd3b54df9b849/build/example.build.js#L553) for minification of the bundled modules written in ES2015+. This is _roughly_ how the build file may look with [terser](https://github.com/terser-js/terser) used as a minification tool (of course, in this case terser should be added as a dependency in your project):
> 
> ```js
> ({
>     // any options you need...
> 
>     optimize: "none", // disable standard uglifyjs optimisations
>     onBuildWrite(moduleName, path, contents) {
>         // r.js overrides `require` saving the original function as `require.nodeRequire`
>         let terser = require.nodeRequire("terser");
>         let result = terser.minify(contents);
>         if (result.error) {
>             throw new Error(result.error);
>         }
>         return result.code;
>     }
> })
> ```

But the `terser.minify` is a async function. so this is not works.

**Comment by Amphiluke** [comment]
@easyfrog,that comment had been written long before `terser.minify` became asynchronous. Well, it appears that the solution is only valid for terser v4. In [their docs](https://github.com/terser/terser/blob/0c5fde1f6951c70b2dfc91f6960dfedbf0e84fef/README.md#api-reference), the developers of terser mention the package [deasync](https://github.com/abbr/deasync) for those who need synchronous solution. Though this looks kind of overkill, it might work nevertheless (haven’t tried myself).

**Comment by easyfrog** [comment]
> @easyfrog,that comment had been written long before `terser.minify` became asynchronous. Well, it appears that the solution is only valid for terser v4. In [their docs](https://github.com/terser/terser/blob/0c5fde1f6951c70b2dfc91f6960dfedbf0e84fef/README.md#api-reference), the developers of terser mention the package [deasync](https://github.com/abbr/deasync) for those who need synchronous solution. Though this looks kind of overkill, it might work nevertheless (haven’t tried myself).

Thanks for your reply, I tried `deasync` package, like this:

`var minify = deasync(terser.minify);`

but still not working, never mind. Continue to use Uglify2. ~👊
