### ISSUE TITLE
Can requirejs build a single optimization output with plugins in cdn?

### ISSUE THREAD

**Issue by trollderius** [requirejs/r.js#982]
**main.js**
```js
requirejs.config({
    css: "https://cdnjs.cloudflare.com/ajax/libs/require-css/0.1.10/css",
    fontawesome: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome"
});
requirejs(["css!fontawesome"]);
```

**app.build.js**
```js
({
    name: "main",
    out: "built.js",
    paths: {
        css: "empty:",
        fontawesome: "empty:",
    }
})
```

**`r.js -o app.build.js` throws:**
```
Error: TypeError: Cannot read property 'normalize' of undefined
In module tree:
    main
```

**Seems that options like 'exclude' only works with modules?**

**Comment by jrburke** [comment]
The plugins need to be available to the optimizer for the build, since only the plugin knows how to resolve its own resources. So I suggest placing copies of the plugins locally for the build, and using the build config to point to those local versions.

Then use [exclude](https://github.com/requirejs/r.js/blob/master/build/example.build.js#L388) in the build config to not include those plugin modules in the output.

Closing as a discussion ticket, but feel free to continue discussion here.
