### ISSUE TITLE
In-browser example for r.js 2.3.5 not working (again?)

### ISSUE THREAD

**Issue by meisl** [requirejs/r.js#987]
#### Rationale (what I can guess) ####
Same symptom as #976 but not a duplicate.
The real problem seems to be with setting up uglify for use in r.js as per [this README](https://github.com/requirejs/r.js/blob/1752638a9b71ce4fc4ac42ce9bcf955ac3c331c8/build/jslib/uglifyjs/README.md).

#### Details ####
I got r.js from the [requirejs.org download page](https://requirejs.org/docs/release/2.3.5/r.js).
Trying the in-browser example [blob/master/tests/browser/r.html](https://github.com/requirejs/r.js/blob/master/tests/browser/r.html)
yields an
```
Uncaught ReferenceError: process is not defined      r-2.3.5.js:24661
```
The mentioned README.md explicitly says
> REMOVE this section:
> ```
> // workaround for tty output truncation upon process.exit()
> [process.stdout, process.stderr].forEach(function(stream){
>     if (stream._handle && stream._handle.setBlocking)
>         stream._handle.setBlocking(true);
> });
> ```
...which are exactly lines  24660 to 24663 in r.js, so that seems to have been forgotten for release 2.3.5.

The README then continues:
> ALSO REMOVE this section:
> ```
>    var path = require("path");
>    var fs = require("fs");
>    ...
> ``` 
I searched r.js for this as well, but didn't find it.

**Comment by jrburke** [comment]
Latest master code does not exhibit this error, looks like the fix for #976 fixed it. How I confirmed it:

* checked out r.js repo
* `git pull origin master`
* I have a `project` folder that contains the r.js repo and requirejs repo, and in that directory I ran `http-server .`
* Opened http://localhost:8080/r.js/tests/browser/r.html
* No errors in console and clicking on the `Build It` button in the web page succeeds.
